name: 'Config Actions Provider'
type: module
description: 'Apply config actions when applying configuration updates.'
core: 8.x
dependencies:
  - 'config_actions:config_actions'
  - 'config_provider:config_provider (>=8.x-2.x)'
  - 'config_sync:config_sync'