name: Commerce Product taxonomy filter
type: module
description: 'Provides taxonomy filter with depth for Drupal Commerce product entity.'
package: Commerce
core: 8.x

dependencies:
  - commerce:commerce
  - drupal:system (>= 8.6)
