name: 'Configuration Import - Delete Entities'
type: module
description: 'If a configuration import detects entities that need to be deleted, this module gives the option to automatically delete them.'
package: 'Other'
core: 8.x
dependencies:
  - config