name: 'Config Pages'
type: module
description: 'Allows the creation of custom configuration entities.'
package: Entity
dependencies:
  - drupal:text
configure: entity.config_pages.collection
core: 8.x
