name: Configuration Share
type: module
description: 'Enable sharing of configuration between multiple extensions and distributions.'
core: 8.x
dependencies:
  - drupal:config
  - 'config_provider:config_provider (>=8.x-2.x)'
