name: drush config import
description: drush config import logging
# core: 8.x
type: module
package: drush
configure: drush_config_import_log.run_import

# Information added by Drupal.org packaging script on 2017-11-27
version: '8.x-1.0'
core: '8.x'
project: 'drush_config_import_log'
datestamp: 1511791694
