name: Config tools
type: module
description: 'Handle logging of changes to configuration, push to a git repo.'
package: Configuration
version: VERSION
core: 8.x
configure: config_tools.settings
dependencies:
