name: Foundation Patterns Configuration
type: module
description: Pre-packaged configuration to jump start the use of the Foundation Patterns theme.
core: 8.x
package: User interface
dependencies:
  - system (>=8.3.0)
  - components
  - field_layout
  - paragraphs
  - ui_patterns
  - ui_patterns_layouts
  - ui_patterns_library