name: Configuration Split Manager
type: module
description: Allows administrator to select modules per environment and those will get exported to separate directories when exporting with 'drush csmex -y' command
core: 8.x
package: Config
configure: config_split_manager.config_split_manager
dependencies:
  - config_split
  - config_filter
