name: 'Config Overlay'
description: 'Manages exported configuration as an overlay of the exported files with module-provided configuration.'
type: module
core: 8.x
package: Config
dependencies:
  - drupal:config_filter
