name: Search Configuration
description: 'Modify search form, including enforcing search restrictions by content type.'
package: Search
core: 8.x
configure: entity.search_page.collection
dependencies:
  - search
type: module
