name: 'Custom Permissions Context'
type: module
description: 'Custom Permissions integration with Context'
core: 8.x
package: 'Custom'
dependencies:
  - context:context
  - config_perms:config_perms (>=8.x-2.x)
