name: 'Locale: Config import'
type: module
description: Allows configuration of the behaviour of interface translation on config import
core: 8.x
package: Multilingual
dependencies:
  - language
  - locale
  - config
configure: config_import_locale.settings
