name: ExtraConfigField
type: module
description: 'Provides extra fields to display and edit config.'
package: Field types
core: 8.x
php: 7.0
configure: entity.extraconfigfield.collection
dependencies:
  - configelement
