name: Config Pages Import
type: module
description: Imports config entities into config pages.
package: Entity
version: '8.x-1.0'
core: '8.x'

configure: config_pages_import_test
config_pages:
  - config_pages_import_test_simple
  - config_pages_import_test_fd

dependencies:
  - config_pages
  - serialization
