name: Development Environment
description: When this module is enabled, the system it is enabled on is marked as a development environment, logging emails to the watchdog instead of sending them out
core: 8.x
type: module
