name: 'Configuration Read-only Menu UI'
type: module
description: 'Allows reordering of content menu links in readonly mode.'
package: Configuration
core: 8.x
dependencies:
  - config_readonly
  - menu_ui
  - menu_link_content