name: Vertical Tabs Config
description: 'Allows you to hide vertical tabs on add/edit node pages depending on content type and role. It also lets you to decide their order.'
type: module
configure: vertical_tabs_config.visibility

core: 8.x
