name: Config Suite
type: module
description: Config Suite is a set of improvements to the configuration management sto make it easier to work with.
core: 8.x
package: Custom
configure: config_suite.config_suite_form
