name: 'Config Export to PHP array'
type: module
description: 'Provides a page like the "Single export" page for getting configuration in PHP array style.'
package: Development
core: 8.x
configure: config2php.export
dependencies:
  - drupal:config
