name: 'Configuration Single Export'
type: module
description: 'Adds an Export button to single configuration export form enabling administrators to export single settings with one click.'
package: Development
version: 8.x-1.0-dev
core: 8.x
dependencies:
  - config
tags:
  - developer
