name: Configuration Distribution
type: module
description: Framework for managing configuration updates from distributions.
core: 8.x
package: Config
dependencies:
  - drupal:config
  - config_filter:config_filter (>=8.x-1.2)
