name: 'Configuration Read-only'
type: module
description: 'Enables making the active configuration store read-only to prevent configuration changes on a Drupal site.'
package: Configuration
core: 8.x
