name: Config Ignore Readonly
description: Whitelists config forms that are ignored when readonly is enabled.
type: module
package: Configuration
core: 8.x

dependencies:
  - config_ignore:config_ignore
  - config_readonly:config_readonly
