name: Environment indicator
type: module
description: Adds a color indicator for the different environments.
package: Development
core: 8.x
dependencies:
  - drupal:color

scripts:
  - js/environment_indicator.js
  - js/color.js

stylesheets:
  all:
    - css/environment_indicator.css

configure: environment_indicator.settings
