name: 'Config Pull Request'
type: module
description: 'Allows administrators to issue pull requests of configuration changed. Github support.'
package: Administration
version: VERSION
core: 8.x
configure: config_pr.settings
dependencies:
  - drupal:config
